version: '3.8'

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true 
      - WDS_SOCKET_HOST=127.0.0.1